#! /bin/bash
#
# motion 3.2.12	(trunk release 550)
# Start the motion detection .
#

NAME=motion
PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON_OPTS="-c /opt/jmps/config/motion.conf"
DAEMON=/opt/jmps/bin/motion
PIDFILE=/var/run/motion/$NAME.pid

trap "" 1
export LANG=C
export PATH
export ERASE_PREVIOUS_IMAGES="YES"
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l1compat.so

test -d /var/run/motion || mkdir /var/run/motion
test -f $DAEMON || exit 0


case "$1" in
  start)
    echo "Starting motion detection : $NAME"
    start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    ;;

  stop)
    echo "Stopping motion detection : $NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --oknodo --exec $DAEMON $DAEMON -- $DAEMON_OPTS --retry 30 
    ;;

  status)
    echo "Status motion detection : $NAME"
    if (test -f $PIDFILE); then
        echo -n "Running process for $NAME : "
    	pidof $NAME  
    else
    	echo "Stopped"
    fi
    ;;  
    
  reload-config)
    echo "Reloading $NAME configuration"
    start-stop-daemon --stop --pidfile $PIDFILE --signal HUP --exec $DAEMON -- $DAEMON_OPTS
    ;;

  restart-motion)
    echo "Restarting $NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --oknodo --exec $DAEMON -- $DAEMON_OPTS --retry 30
    start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    ;;

  restart)
    $0 restart-motion
    exit $?
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|status|reload-config|restart}"
    exit 1
    ;;
esac

if [ $? == 0 ]; then
	echo .
	exit 0
else
	echo failed
	exit 1
fi
