/*
 * © 2013 Gilbarco Inc.
 * Confidential and Proprietary
 *
 * @file GSPOTDashboardMainGUIChild.h
 * @author Sebastian Lipchak
 * @date Oct 02 2013
 * @copyright © 2013 Gilbarco Inc. Confidential and Propietary
 */


#ifndef __GSPOTDashboardMainGUIChild__
#define __GSPOTDashboardMainGUIChild__

/**
@file
Subclass of GSPOTDashboardMainGUI, which is generated by wxFormBuilder.
*/

#include "GSPOTDashboardMainGUI.h"

//// end generated include

/** Implementing GSPOTDashboardMainGUI */
class GSPOTDashboardMainGUIChild : public GSPOTDashboardMainGUI
{
	protected:
		// Handlers for GSPOTDashboardMainGUI events.
		void OnQuit( wxCommandEvent& event );
		void OnRefresh( wxCommandEvent& event );
	public:
		/** Constructor */
		GSPOTDashboardMainGUIChild( wxWindow* parent );
	//// end generated class members
	
};

#endif // __GSPOTDashboardMainGUIChild__
