##-#######################################################################-##
# Copyright © 2014 Gilbarco Inc.
# Confidential and Proprietary.
#
## @file GvrExport.cmake
## @author pcantarini
## @date Tuesday, April 22, 2014
## @copyright Copyright © 2014 Gilbarco Inc. Confidential and Proprietary.
##-#######################################################################-##

cmake_minimum_required(VERSION 2.8.1 FATAL_ERROR)

if (NOT DEFINED GVR_EXPORT_INCLUDED)
  set(GVR_EXPORT_INCLUDED ON)

  ############### GVR Support Definitions ###############
  function (GVR_EXPORT)
    include(CMakeParseArguments)
    include(CMakePackageConfigHelpers)
    set(GVR_FLAGS EXTERNAL APPEND)
    set(GVR_SINGLE_VALUE NAME DESTINATION_LOCATION EXTERNAL_PREFIX_LOCATION COPYRIGHT VERSION COMPATIBILITY CODE)
# Removed namespace from options as it complicates implicit find_library on importing projects.
#    set(GVR_SINGLE_VALUE ${GVR_SINGLE_VALUE} NAMESPACE)
    set(GVR_MULTI_VALUE DEFINITIONS INCLUDES LINK_LOCATIONS COMMAND_LOCATIONS TARGETS)
    cmake_parse_arguments(GVR_EXPORT "${GVR_FLAGS}" "${GVR_SINGLE_VALUE}" "${GVR_MULTI_VALUE}" ${ARGN})

    if (GVR_EXPORT_NAME)
      if (GVR_EXPORT_DESTINATION_LOCATION)
        file(TO_CMAKE_PATH "${GVR_EXPORT_DESTINATION_LOCATION}" GVR_EXPORT_DESTINATION_LOCATION)
        set(GVR_EXPORT_DESTINATION_LOCATION "${GVR_EXPORT_DESTINATION_LOCATION}/")
      else (GVR_EXPORT_DESTINATION_LOCATION)
        set(GVR_EXPORT_DESTINATION_LOCATION "")
      endif (GVR_EXPORT_DESTINATION_LOCATION)

      if (GVR_EXPORT_EXTERNAL_PREFIX_LOCATION)
        file(TO_CMAKE_PATH "${GVR_EXPORT_EXTERNAL_PREFIX_LOCATION}" GVR_EXPORT_EXTERNAL_PREFIX_LOCATION)
        set(GVR_EXPORT_EXTERNAL ON)
      endif (GVR_EXPORT_EXTERNAL_PREFIX_LOCATION)

      if (GVR_EXPORT_APPEND AND (GVR_EXPORT_EXTERNAL OR GVR_EXPORT_EXTERNAL_PREFIX_LOCATION OR GVR_EXPORT_COPYRIGHT OR GVR_EXPORT_VERSION OR GVR_EXPORT_COMPATIBILITY))
        if (EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake")
          if (GVR_EXPORT_EXTERNAL)
            message(WARNING "Appending to file '${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake' and ingnoring variable EXTERNAL '${GVR_EXPORT_EXTERNAL}'.")
          endif (GVR_EXPORT_EXTERNAL)
          if (GVR_EXPORT_EXTERNAL_PREFIX_LOCATION)
            message(WARNING "Appending to file '${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake' and ingnoring variable EXTERNAL_PREFIX_LOCATION '${GVR_EXPORT_EXTERNAL_PREFIX_LOCATION}'.")
          endif (GVR_EXPORT_EXTERNAL_PREFIX_LOCATION)
          if (GVR_EXPORT_COPYRIGHT)
            message(WARNING "Appending to file '${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake' and ingnoring variable COPYRIGHT '${GVR_EXPORT_COPYRIGHT}'.")
          endif (GVR_EXPORT_COPYRIGHT)
        endif (EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake")
        if (EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}ConfigVersion.cmake")
          if (GVR_EXPORT_VERSION)
            message(WARNING "Appending to file '${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}ConfigVersion.cmake' and ingnoring variable VERSION '${GVR_EXPORT_VERSION}'.")
          endif (GVR_EXPORT_VERSION)
          if (GVR_EXPORT_COMPATIBILITY)
            message(WARNING "Appending to file '${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}ConfigVersion.cmake' and ingnoring variable COMPATIBILITY '${GVR_EXPORT_COMPATIBILITY}'.")
          endif (GVR_EXPORT_COMPATIBILITY)
        endif (EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}ConfigVersion.cmake")
      endif (GVR_EXPORT_APPEND AND (GVR_EXPORT_EXTERNAL OR GVR_EXPORT_EXTERNAL_PREFIX_LOCATION OR GVR_EXPORT_COPYRIGHT OR GVR_EXPORT_VERSION OR GVR_EXPORT_COMPATIBILITY))

      if ((GVR_EXPORT_EXTERNAL AND GVR_EXPORT_EXTERNAL_PREFIX_LOCATION) OR (NOT GVR_EXPORT_EXTERNAL))
#        if (GVR_EXPORT_NAMESPACE)
#          set(GVR_EXPORT_NAMESPACE_ON_EXPORT NAMESPACE ${GVR_EXPORT_NAMESPACE})
#        else (GVR_EXPORT_NAMESPACE)
#          set(GVR_EXPORT_NAMESPACE "")
#          set(GVR_EXPORT_NAMESPACE_ON_EXPORT "")
#        endif (GVR_EXPORT_NAMESPACE)

        if (GVR_EXPORT_COPYRIGHT)
          set(GVR_EXPORT_COPYRIGHT "## Copyright: ${GVR_EXPORT_COPYRIGHT} ##")
        else (GVR_EXPORT_COPYRIGHT)
          set(GVR_EXPORT_COPYRIGHT "")
        endif (GVR_EXPORT_COPYRIGHT)

        if (GVR_EXPORT_VERSION)
          set(GVR_EXPORT_VERSION_ARGUMENT VERSION ${GVR_EXPORT_VERSION})
        else (GVR_EXPORT_VERSION)
          set(GVR_EXPORT_VERSION "")
          set(GVR_EXPORT_VERSION_ARGUMENT "")
        endif (GVR_EXPORT_VERSION)

        if (GVR_EXPORT_COMPATIBILITY)
          set(GVR_EXPORT_COMPATIBILITY COMPATIBILITY ${GVR_EXPORT_COMPATIBILITY})
        else (GVR_EXPORT_COMPATIBILITY)
          set(GVR_EXPORT_COMPATIBILITY "")
        endif (GVR_EXPORT_COMPATIBILITY)

        if (NOT GVR_EXPORT_CODE)
          set(GVR_EXPORT_CODE "")
        endif (NOT GVR_EXPORT_CODE)

        if (GVR_EXPORT_DEFINITIONS)
          list(REMOVE_DUPLICATES GVR_EXPORT_DEFINITIONS)
        endif (GVR_EXPORT_DEFINITIONS)

        if (GVR_EXPORT_INCLUDES)
          list(REMOVE_DUPLICATES GVR_EXPORT_INCLUDES)
        endif (GVR_EXPORT_INCLUDES)

        if (GVR_EXPORT_LINK_LOCATIONS)
          list(REMOVE_DUPLICATES GVR_EXPORT_LINK_LOCATIONS)
        endif (GVR_EXPORT_LINK_LOCATIONS)

        if (GVR_EXPORT_COMMAND_LOCATIONS)
          list(REMOVE_DUPLICATES GVR_EXPORT_COMMAND_LOCATIONS)
        endif (GVR_EXPORT_COMMAND_LOCATIONS)

        if (GVR_EXPORT_TARGETS)
          list(REMOVE_DUPLICATES GVR_EXPORT_TARGETS)
        endif (GVR_EXPORT_TARGETS)

        set(${GVR_EXPORT_NAME}_IMPORTED_INCLUDES "")
        foreach (GVR_EXPORT_INCLUDE ${GVR_EXPORT_INCLUDES})
          file(TO_CMAKE_PATH "${GVR_EXPORT_INCLUDE}" GVR_EXPORT_INCLUDE)
          set(${GVR_EXPORT_NAME}_IMPORTED_INCLUDES ${${GVR_EXPORT_NAME}_IMPORTED_INCLUDES} "${GVR_EXPORT_INCLUDE}")
        endforeach (GVR_EXPORT_INCLUDE)

        set(${GVR_EXPORT_NAME}_IMPORTED_LINK_LOCATIONS "")
        foreach (GVR_EXPORT_LINK_LOCATION ${GVR_EXPORT_LINK_LOCATIONS})
          file(TO_CMAKE_PATH "${GVR_EXPORT_LINK_LOCATION}" GVR_EXPORT_LINK_LOCATION)
          set(${GVR_EXPORT_NAME}_IMPORTED_LINK_LOCATIONS ${${GVR_EXPORT_NAME}_IMPORTED_LINK_LOCATIONS} "${GVR_EXPORT_LINK_LOCATION}")
        endforeach (GVR_EXPORT_LINK_LOCATION)

        set(${GVR_EXPORT_NAME}_IMPORTED_COMMAND_LOCATIONS "")
        foreach (GVR_EXPORT_COMMAND_LOCATION ${GVR_EXPORT_COMMAND_LOCATIONS})
          file(TO_CMAKE_PATH "${GVR_EXPORT_COMMAND_LOCATION}" GVR_EXPORT_COMMAND_LOCATION)
          set(${GVR_EXPORT_NAME}_IMPORTED_COMMAND_LOCATIONS ${${GVR_EXPORT_NAME}_IMPORTED_COMMAND_LOCATIONS} "${GVR_EXPORT_COMMAND_LOCATION}")
        endforeach (GVR_EXPORT_COMMAND_LOCATION)

        if (NOT GVR_EXPORT_APPEND)
          file(GLOB ${GVR_EXPORT_NAME}_CONFIG_FILES "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config*.cmake")
          if (${GVR_EXPORT_NAME}_CONFIG_FILES)
            file(REMOVE ${GVR_EXPORT_NAME}_CONFIG_FILES)
          endif (${GVR_EXPORT_NAME}_CONFIG_FILES)
        endif (NOT GVR_EXPORT_APPEND)

        if (NOT GVR_EXPORT_APPEND OR NOT EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake")
          file(WRITE "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "${GVR_EXPORT_COPYRIGHT}
cmake_minimum_required(VERSION ${CMAKE_VERSION} FATAL_ERROR)
if (${GVR_EXPORT_NAME}_IMPORTED)
  return()
endif (${GVR_EXPORT_NAME}_IMPORTED)

set(${GVR_EXPORT_NAME}_IMPORTED ON)
set(${GVR_EXPORT_NAME}_VERSION ${GVR_EXPORT_VERSION})
")

          if (GVR_EXPORT_EXTERNAL)
            file(APPEND "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "
set(${GVR_EXPORT_NAME}_IMPORTED_EXTERNAL ${GVR_EXPORT_EXTERNAL})
set(${GVR_EXPORT_NAME}_IMPORTED_EXTERNAL_PREFIX_LOCATION ${GVR_EXPORT_EXTERNAL_PREFIX_LOCATION})
")
          endif (GVR_EXPORT_EXTERNAL)
        endif (NOT GVR_EXPORT_APPEND OR NOT EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake")

        if (EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake")
          if (GVR_EXPORT_DEFINITIONS)
            file(APPEND "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "
set(${GVR_EXPORT_NAME}_IMPORTED_DEFINITIONS \${${GVR_EXPORT_NAME}_IMPORTED_DEFINITIONS} ${GVR_EXPORT_DEFINITIONS})
")
          endif (GVR_EXPORT_DEFINITIONS)

          if (${GVR_EXPORT_NAME}_IMPORTED_INCLUDES)
            file(APPEND "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "
set(${GVR_EXPORT_NAME}_IMPORTED_INCLUDES \${${GVR_EXPORT_NAME}_IMPORTED_INCLUDES} ${${GVR_EXPORT_NAME}_IMPORTED_INCLUDES})
")
          endif (${GVR_EXPORT_NAME}_IMPORTED_INCLUDES)

          if (${GVR_EXPORT_NAME}_IMPORTED_LINK_LOCATIONS)
            file(APPEND "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "
set(${GVR_EXPORT_NAME}_IMPORTED_LINK_LOCATIONS \${${GVR_EXPORT_NAME}_IMPORTED_LINK_LOCATIONS} ${${GVR_EXPORT_NAME}_IMPORTED_LINK_LOCATIONS})
")
          endif (${GVR_EXPORT_NAME}_IMPORTED_LINK_LOCATIONS)

          if (${GVR_EXPORT_NAME}_IMPORTED_COMMAND_LOCATIONS)
            file(APPEND "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "
set(${GVR_EXPORT_NAME}_IMPORTED_COMMAND_LOCATIONS \${${GVR_EXPORT_NAME}_IMPORTED_COMMAND_LOCATIONS} ${${GVR_EXPORT_NAME}_IMPORTED_COMMAND_LOCATIONS})
")
          endif (${GVR_EXPORT_NAME}_IMPORTED_COMMAND_LOCATIONS)

          if (GVR_EXPORT_TARGETS)
            foreach (GVR_EXPORT_TARGET ${GVR_EXPORT_TARGETS})
              if (TARGET ${GVR_EXPORT_TARGET})
                get_target_property(GVR_EXPORT_TARGET_TYPE ${GVR_EXPORT_TARGET} TYPE)
                set(GVR_EXPORT_TARGET_NAME ${GVR_EXPORT_TARGET})
#                if (GVR_EXPORT_NAMESPACE)
#                  set(GVR_EXPORT_TARGET_NAME ${GVR_EXPORT_NAMESPACE}_${GVR_EXPORT_TARGET_NAME})
#                endif (GVR_EXPORT_NAMESPACE)

                file(APPEND  "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "

set(${GVR_EXPORT_NAME}_IMPORTED_TARGETS \${${GVR_EXPORT_NAME}_IMPORTED_TARGETS} ${GVR_EXPORT_TARGET_NAME})
set(${GVR_EXPORT_NAME}_IMPORTED_${GVR_EXPORT_TARGET_TYPE}_TARGETS \${${GVR_EXPORT_NAME}_IMPORTED_${GVR_EXPORT_TARGET_TYPE}_TARGETS} ${GVR_EXPORT_TARGET_NAME})
")
##-###############################################################################################################-##
# Excluded due to an issue which involves having to place all information on target if explicitly declared as IMPORTED target
# If not declared as target link_directories() function in imported projects will find the targets.
#
#                # Exclude imported externalproject targets as there is an issue with exporting them.
#                get_target_property(GVR_EXPORT_TARGET_IS_IMPORTED ${GVR_EXPORT_TARGET} IMPORTED)
#                if (NOT GVR_EXPORT_TARGET_IS_IMPORTED)
#                  file(APPEND  "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "
#if (NOT TARGET ${GVR_EXPORT_TARGET_NAME})
#
#")
#                export(TARGETS ${GVR_EXPORT_TARGET} ${GVR_EXPORT_NAMESPACE_ON_EXPORT}
#                        APPEND FILE "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake")
#
#                file(APPEND  "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "
#endif (NOT TARGET ${GVR_EXPORT_TARGET_NAME})
#")
#                endif (NOT GVR_EXPORT_TARGET_IS_IMPORTED)
##-###############################################################################################################-##
              else (TARGET ${GVR_EXPORT_TARGET})
                message(WARNING "GVR_EXPORT unable to export invalid TARGET '${GVR_EXPORT_TARGET}'.")
              endif (TARGET ${GVR_EXPORT_TARGET})
            endforeach (GVR_EXPORT_TARGET)
          endif (GVR_EXPORT_TARGETS)

          if (GVR_EXPORT_CODE)
          file(APPEND "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake" "
"
${GVR_EXPORT_CODE}
"
")
          endif (GVR_EXPORT_CODE)
        endif (EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}Config.cmake")

        if (NOT GVR_EXPORT_APPEND OR NOT EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}ConfigVersion.cmake")
          write_basic_package_version_file("${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}ConfigVersion.cmake" ${GVR_EXPORT_VERSION_ARGUMENT} ${GVR_EXPORT_COMPATIBILITY})
        endif (NOT GVR_EXPORT_APPEND OR NOT EXISTS "${GVR_EXPORT_DESTINATION_LOCATION}${GVR_EXPORT_NAME}ConfigVersion.cmake")

      else ((GVR_EXPORT_EXTERNAL AND GVR_EXPORT_EXTERNAL_PREFIX_LOCATION) OR (NOT GVR_EXPORT_EXTERNAL))
        message(FATAL_ERROR "GVR_EXPORT called with EXTERNAL setted and no EXTERNAL_PREFIX_LOCATION provided.")
      endif ((GVR_EXPORT_EXTERNAL AND GVR_EXPORT_EXTERNAL_PREFIX_LOCATION) OR (NOT GVR_EXPORT_EXTERNAL))
    else (GVR_EXPORT_NAME)
      message(FATAL_ERROR "GVR_EXPORT called without exportable NAME.")
    endif (GVR_EXPORT_NAME)
  endfunction (GVR_EXPORT)
endif (NOT DEFINED GVR_EXPORT_INCLUDED)
